### PR TITLE
Override box-shadow and border from frost-button

### PR DESCRIPTION
**Pull request by laflower**
# fix

remove glow around focused frost-tab 

frost-tabsglow

### CODE REVIEW

**Comment by sglanzer-fire** [comment]
Good stuff, this was bugging me too - can you sync with @vesper2000 in case you have overlapping changes?  I believe she's also doing work in the tab area

**Comment by laflower** [comment]
build not triggering

**Comment by sglanzer-fire** [comment]
When the build doesn't trigger is it that Travis is pending or that it's not present at all?

**Comment by vesper2000** [comment]
I have it all fixed up with the new `design` property for button.  I have my PR out for frost-button and frost-tabs PR will be coming out as soon as merged build passes for button. 
So this PR can be cancelled as I will be overwriting your changes.

**Comment by laflower** [comment]
@sglanzer It wasn't showing here https://travis-ci.org/ciena-frost/ember-frost-tabs/pull_requests
And it wasn't listed as a pending check here either.

**Comment by sglanzer-fire** [comment]
Closing as per @vesper2000 comments, thanks for confirming - @laflower if you have any concerns please coordinate with @vesper2000

**Comment by vesper2000** [comment]
This is the look after my changes will go in.  
image

image

**Pull request closed without merging**
