### PR TITLE
update version ember-frost-core

### PR DESCRIPTION
**Pull request by EWhite613**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [ ] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [x] #major# - incompatible API change

# CHANGELOG
* Use the latest `ember-frost-core`, with a flexible minor version (`^3.0.1`)

### CODE REVIEW

**Comment by juwara0** [comment]
The blueprint will need to be updated as well.

**Review by notmessenger — CHANGES_REQUESTED** [review]
* The blueprint needs to be updated as well.
* Your Changelog entry is not accurate - you are using latest major
* This PR cannot be a patch - you have changed a dependency to a new major.

**Comment by juwara0** [comment]
This will need to be a server major since you are moving the version of core up a major.

**Review by notmessenger — APPROVED** [review]

**Comment by notmessenger** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-tabs/pull-request/70/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-tabs)

**Pull request merged**
