### PR TITLE
removed a line of css to make block format and regular format have same styling

### PR DESCRIPTION
**Pull request by cstolli**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* removed two lines of CSS to reduce specificity of style rule targeting the `.tab` class.  Because non-block-format mode has an additional div around each tab, and the CSS was targeting it specifically, block-format tabs were not the same style (larger font, no border, etc) as non-block tabs.

### CODE REVIEW

**Comment by notmessenger** [comment]
@cstolli is failing linting

**Comment by cstolli** [comment]
@notmessenger thanks, fixed

**Comment by notmessenger** [comment]
👍 This is a rubber-stamp approval as I do not have enough contextual knowledge to asses the impact of this change.

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-tabs/pull-request/68/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-tabs)

**Comment by cstolli** [comment]
@notmessenger I'm having @EWhite613 sanity check this for additional approval

**Comment by EWhite613** [comment]
Approved

**Comment by EWhite613** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-tabs/pull-request/68/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-tabs)

**Pull request merged**
