### PR TITLE
Updated blueprint to use ember-frost-core@^1.0.3

### PR DESCRIPTION
**Pull request by NickLewanowicz**
### This project uses [semver](semver.org), please check the scope of this pr:
 - [x] #patch# - backwards-compatible bug fix
 - [ ] #minor# - adding functionality in a backwards-compatible manner
 - [ ] #major# - incompatible API change

# CHANGELOG
* **Updated** blueprint with latest core

### CODE REVIEW

**Review by dafortin — COMMENTED** [review]
Remove the .DS_Store file please

**Comment by dafortin** [comment]
Build failing because of the following issue: https://github.com/stonecircle/ember-cli-notifications/issues/131

**Comment by ynnoj** [comment]
@dafortin Sorry about the issues with `ember-cli-notifications`. I just published `4.1.4` which fixes the issue breaking your build.

**Comment by dafortin** [comment]
@ynnoj no worries. Thanks for fixing :) 👍

**Pull request merged**
